# Generated by Django 5.0.4 on 2024-04-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cars_delete_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='name',
            new_name='car_name',
        ),
    ]
